/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pizzaria;

import java.text.NumberFormat;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SoldierJVX
 */
public class FormCadastrarPedido extends javax.swing.JFrame {

    /**
     * Creates new form FormCadastrarPedido
     */
    FormMenuFuncionario frmMenu;
    FormLoginCliente frmCliente;

    Cliente acessando;
    Funcionario quemFez;

    private double total;

    ArrayList<Produto> listaProdutos;
    ArrayList<Pedido> listaPedidos;
    ArrayList<Cliente> listaClientes;

    public FormCadastrarPedido(FormMenuFuncionario frmMenu) {
        initComponents();

        this.frmMenu = frmMenu;
        this.listaProdutos = frmMenu.listaProdutos;
        this.listaPedidos = frmMenu.listaPedidos;
        this.listaClientes = frmMenu.listaClientes;
        this.quemFez = frmMenu.acessando;

        total = 0;

        txtNumeroPedido.setText((listaPedidos.size() + 1) + "");

        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    public FormCadastrarPedido(FormLoginCliente frmCliente, Cliente acessando) {
        initComponents();

        this.frmCliente = frmCliente;
        this.acessando = acessando;
        this.listaProdutos = frmCliente.listaProdutos;
        this.listaPedidos = frmCliente.listaPedidos;
        this.listaClientes = frmCliente.listaClientes;

        total = 0;

        txtNumeroPedido.setText((listaPedidos.size() + 1) + "");

        txtNumCli.setEditable(false);
        getTxtNumCli().setText(frmCliente.getTxtTelefone().getText());

        btnBuscarActionPerformed(null);
        btnBuscar.setEnabled(false);

        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    public double getTotal() {
        return total;
    }

    public void setTotal(double total) {
        this.total = total;
    }

    public JTable getTblListaProdutos() {
        return tblListaProdutos;
    }

    public JTextField getTxtTotal() {
        return txtTotal;
    }

    public JButton getBtnRemoverProduto() {
        return btnRemoverProduto;
    }

    public JFormattedTextField getTxtNumCli() {
        return txtNumCli;
    }

    public JButton getBtnBuscar() {
        return btnBuscar;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNumeroPedido = new javax.swing.JTextField();
        btnAddProduto = new javax.swing.JButton();
        btnRemoverProduto = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListaProdutos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btnFinalizarPedido = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        txtNumCli = new javax.swing.JFormattedTextField();
        txtTotal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pizzaria - Cadastrar Pedido");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("Número do Pedido: ");

        txtNumeroPedido.setEditable(false);

        btnAddProduto.setText("Adicionar Produto");
        btnAddProduto.setEnabled(false);
        btnAddProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProdutoActionPerformed(evt);
            }
        });

        btnRemoverProduto.setText("Remover Produto");
        btnRemoverProduto.setEnabled(false);
        btnRemoverProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverProdutoActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        tblListaProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código do Produto", "Nome", "Preço", "Quantidade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblListaProdutos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblListaProdutos.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tblListaProdutosPropertyChange(evt);
            }
        });
        tblListaProdutos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblListaProdutosKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblListaProdutos);

        jLabel2.setText("Valor Total:");

        btnFinalizarPedido.setText("Finalizar Pedido");
        btnFinalizarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarPedidoActionPerformed(evt);
            }
        });

        jLabel3.setText("Número do Cliente:");

        jLabel4.setText("Nome do Cliente:");

        txtNome.setEditable(false);

        jLabel5.setText("Endereço Entrega:");

        txtEndereco.setEditable(false);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        try {
            txtNumCli.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        txtTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTotal.setText("R$: 0,00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 615, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNumeroPedido)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtNumCli)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscar))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3))
                            .addComponent(jLabel5))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEndereco)
                            .addComponent(txtNome)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnFinalizarPedido)
                                .addGap(0, 429, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAddProduto)
                                .addGap(18, 18, 18)
                                .addComponent(btnRemoverProduto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtTotal)
                                .addGap(2, 2, 2))
                            .addComponent(btnCancelar))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtNumeroPedido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(btnBuscar)
                    .addComponent(txtNumCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAddProduto)
                        .addComponent(btnRemoverProduto))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnFinalizarPedido))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed

        if (frmMenu != null) {

            frmMenu.setEnabled(true);

        } else {

            new FormSelecaoUsuario(frmCliente.getListaFuncionarios(), frmCliente.getListaClientes(), frmCliente.getListaProdutos(), frmCliente.getListaPedidos());

        }

        this.dispose();

    }//GEN-LAST:event_btnCancelarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

        btnCancelarActionPerformed(null);

    }//GEN-LAST:event_formWindowClosing

    private void btnAddProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProdutoActionPerformed
        this.setEnabled(false);
        new FormAdicionarProduto(this);
    }//GEN-LAST:event_btnAddProdutoActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        txtNome.setText("");
        txtEndereco.setText("");
        
        String telCliente = txtNumCli.getText();
        Cliente cliente = null;

        if (telCliente.matches("\\(\\d{2}\\)\\d{4,5}-\\d{4}")) {

            cliente = Buscas.buscaCliente(listaClientes, telCliente);

            if (cliente == null) {

                JOptionPane.showMessageDialog(null, "Cliente não encontrado!", "Não Encontrado", JOptionPane.INFORMATION_MESSAGE);

                btnAddProduto.setEnabled(false);

                return;

            }

            btnAddProduto.setEnabled(true);

            this.acessando = cliente;

            txtNome.setText(cliente.getNome());
            txtEndereco.setText(cliente.getEndereco());
            

        } else {

            JOptionPane.showMessageDialog(null, "Número de telefone inválido!", "Erro", JOptionPane.WARNING_MESSAGE);

        }


    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnFinalizarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarPedidoActionPerformed

        
        if (getTotal() == 0) {
            JOptionPane.showMessageDialog(null, "Adicione um produto","Sem produtos na lista", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        int numPedido = Integer.parseInt(txtNumeroPedido.getText()) - 1;
        double total = getTotal();
        ArrayList<Produto> produtosPedido = new ArrayList<>();
        Cliente acessando = this.acessando;

        int codProduto;
        int quantidade;
        Produto aAdicionar;

        for (int i = 0; i < tblListaProdutos.getRowCount(); i++) {

            codProduto = (Integer) tblListaProdutos.getValueAt(i, 0) - 1;
            quantidade = (Integer) tblListaProdutos.getValueAt(i, 3);

            aAdicionar = listaProdutos.get(codProduto);

            for (int j = 0; j < quantidade; j++) {
                produtosPedido.add(aAdicionar);
            }

        }

        listaPedidos.add(new Pedido(numPedido, total, produtosPedido, this.quemFez, acessando));

        JOptionPane.showMessageDialog(null, "Pedido Realizado com sucesso!", "Pedido Realizado", JOptionPane.INFORMATION_MESSAGE);

        btnCancelarActionPerformed(evt);


    }//GEN-LAST:event_btnFinalizarPedidoActionPerformed

    private void btnRemoverProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverProdutoActionPerformed

        if (tblListaProdutos.getSelectedRow() != -1) {

            DefaultTableModel modelo = (DefaultTableModel) tblListaProdutos.getModel();
            NumberFormat formatador = NumberFormat.getCurrencyInstance();

            int quantidade = (Integer) modelo.getValueAt(tblListaProdutos.getSelectedRow(), 3);
            int codProduto = (Integer) modelo.getValueAt(tblListaProdutos.getSelectedRow(), 0);

            double preco = listaProdutos.get(codProduto - 1).getPreco();
            double total = getTotal();

            total -= quantidade * preco;
            modelo.removeRow(tblListaProdutos.getSelectedRow());

            if (tblListaProdutos.getRowCount() == 0) {

                btnRemoverProduto.setEnabled(false);

            } else {
                btnRemoverProduto.setEnabled(true);

            }

            tblListaProdutos.setModel(modelo);

            setTotal(total);
            txtTotal.setText(formatador.format(total));

        }


    }//GEN-LAST:event_btnRemoverProdutoActionPerformed

    private void tblListaProdutosPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tblListaProdutosPropertyChange
    }//GEN-LAST:event_tblListaProdutosPropertyChange

    private void tblListaProdutosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblListaProdutosKeyReleased
    }//GEN-LAST:event_tblListaProdutosKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddProduto;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnFinalizarPedido;
    private javax.swing.JButton btnRemoverProduto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblListaProdutos;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtNome;
    private javax.swing.JFormattedTextField txtNumCli;
    private javax.swing.JTextField txtNumeroPedido;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables

}
